Hw01 hello is completed
abeniaminov/home_work pull request #1
Opened 2023-06-04 21:40 UTC by abeniaminov

2023-06-05 10:56 UTC, dshemin requested changes

2023-06-05 10:56 UTC, dshemin commented on hw01_hello_otus/go.mod
>  module github.com/fixme_my_friend/hw01_hello_otus
Критично:

Модуль должен быть go gettable, тут надо поправить. должно быть `module github.com/abeniaminov/home_work/hw01_hello_otus`

2023-06-06 09:46 UTC, abeniaminov commented on hw01_hello_otus/go.mod
>  module github.com/fixme_my_friend/hw01_hello_otus
Точно, спасибо!

2023-06-06 10:58 UTC, dshemin approved these changes

2023-06-07 14:52 UTC, merged