HW08 is completed
abeniaminov/home_work pull request #9
Opened 2023-09-04 22:27 UTC by abeniaminov

## Домашнее задание №8 «Утилита envdir»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-09-05 06:54 UTC, dshemin requested changes

2023-09-05 06:54 UTC, dshemin commented on hw08_envdir_tool/env_reader.go
> +		if fpStat.Mode().IsRegular() {
Критично:

Нет проверки на то, что имя файла содержит `=`, обратите внимание на текст задания

2023-09-05 06:54 UTC, dshemin commented on hw08_envdir_tool/env_reader_test.go
> +		if err != nil {
Важно:

Лучше require.NoError

2023-09-05 06:54 UTC, dshemin commented on hw08_envdir_tool/env_reader_test.go
> +	t.Run("path not exists", func(t *testing.T) {
Важно:

Данный тест можно сильно упростить, избавившись от повторяющегося кода если использовать табличные тесты.

https://dave.cheney.net/2019/05/07/prefer-table-driven-tests

2023-09-05 06:54 UTC, dshemin commented on hw08_envdir_tool/executor.go
> +	eCmd.Stdout = os.Stdout
Критично:

Нет перенаправления stdin и stderr.

2023-09-05 06:54 UTC, dshemin commented on hw08_envdir_tool/executor_test.go
> +		require.Equal(t, ok, true)
Важно:

Есть require.True()

2023-09-05 06:54 UTC, dshemin commented on hw08_envdir_tool/executor_test.go
> +	t.Run("fail exec multiline test", func(t *testing.T) {
Важно:

Тут тоже табличный тест применим.

2023-09-05 06:54 UTC, dshemin commented on hw08_envdir_tool/executor.go
> +		return errCode(err)
Критично:

Учитывая реализацию errCode, то тут будет неверное поведение. Вместо 1 нам надо вернуть exit code того процесса который мы запустили.

2023-09-05 21:09 UTC, abeniaminov commented on hw08_envdir_tool/env_reader.go
> +		if fpStat.Mode().IsRegular() {
вставил проверку, 
но как вы думаете, если в директории хоть один файл содержит =, то прерывать выполнение или игнорировать такой файл?
Я пока игнорирую

2023-09-05 21:10 UTC, abeniaminov commented on hw08_envdir_tool/env_reader_test.go
> +		if err != nil {
Принято

2023-09-05 21:10 UTC, abeniaminov commented on hw08_envdir_tool/env_reader_test.go
> +	t.Run("path not exists", func(t *testing.T) {
переделал

2023-09-05 21:10 UTC, abeniaminov commented on hw08_envdir_tool/executor.go
> +	eCmd.Stdout = os.Stdout
добавил

2023-09-05 21:10 UTC, abeniaminov commented on hw08_envdir_tool/executor_test.go
> +		require.Equal(t, ok, true)
принято

2023-09-05 21:11 UTC, abeniaminov commented on hw08_envdir_tool/executor_test.go
> +	t.Run("fail exec multiline test", func(t *testing.T) {
переделал

2023-09-05 21:12 UTC, abeniaminov commented on hw08_envdir_tool/executor.go
> +		return errCode(err)
использовал *exec.ExitError. Тест написал

2023-09-05 21:36 UTC, abeniaminov commented on hw08_envdir_tool/executor.go
> +		return errCode(err)
Интересно, что на Ubuntu и на macos выдает разный код

2023-09-06 00:42 UTC, dshemin commented on hw08_envdir_tool/env_reader.go
> +		if fpStat.Mode().IsRegular() {
Просто игнорировать. Всё верно.

2023-09-06 00:43 UTC, dshemin approved these changes

2023-09-06 06:33 UTC, merged